version: "3.8"
services:
  ccb-ui:
    image: "ccb-ui:local"
    tty: true
    build:
      context: ../ccb_ui
    ports:
        - 3000:3000
    restart: always
    volumes:
      - ../ccb_ui/src:/usr/app/src
    # environment:
    #   REACT_APP_API_URL: http://ccb-api:4000
    depends_on:
      - ccb-api
    
  ccb-api:
    image: "ccb-api:local"
    build:
      context: .
    ports:
      - 4000:4000
    restart: always
    environment:
      DATABASE_URL: ecto://postgres:postgres@postgres/ccb_prod
      ECTO_CLOAK_KEY: cGFzc3dvcmQ=
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres

  