use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :ccb_api, CcbApiWeb.Endpoint,
  url: [host: "example.com", port: 80],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :ccb_api, CcbApiWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH"),
#         transport_options: [socket_opts: [:inet6]]
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :ccb_api, CcbApiWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# Setup Guardian with Auth0
# config :ccb_api, Auth.Guardian,
#   allowed_drift: 30_000,
#   allowed_algos: ["RS256"],
#   verify_module: Guardian.JWT,
#   issuer: "https://ccbapp.eu.auth0.com/",
#   verify_issuer: false,
#   secret_key_pem_path: "ccbapp.pem",
#   secret_key: {Auth.Guardian.SecretKey, :fetch, []}

# Configure Guardian for JWT Authentication
config :ccb_api, Auth.Guardian,
  allowed_algos: ["RS256"],
  secret_key: {Auth.Guardian.SecretKey, :fetch_from_binary, []},
  secret_binary: """
    {
        "alg": "RS256",
        "e": "AQAB",
        "n": "vPLUo5EEMafO4bWYkK490-IgO45dbm1r9En7OIb_f1r7drzSepEq2RW7npjPUVOZWQRzZ9u5klWy-eDUrjwSoJf8GHUWzWBVoTkWZgHFgy72ESobjJbTfJLLTIK8MIvRSWnDkcQl2DrpLfrLm1aQdWeppqGKgu3ojcn3BfvuOnd-qb2c_bNC7-ec1uxr5Q5xzb5JKEyWCK476Lp8iK8WptJShnHBa7lAqlSOj2kRzQ77B4i-ehQvBNKi6jfNKEgqnW34OXSiqJKmfs2PuH-qLdDfLccsRFqwau38yzpHIa6LpczuScHXAC6fg_tiWhvy5FICwM0TKlb8GKkFr03Ngw",
        "kid": "MpNwYoEgkamunPRmCLBZ1P2sMOxo6pJAqDpUbiySlLI",
        "kty": "RSA",
        "use": "sig"
      }
  """

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"
